version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - /.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_eleitoral:/var/lib/postgresql/data
    deploy:
      replicas: 1

  minio:
    image: minio/minio:latest
    env_file:
      - /.env
    ports:
      - "9090:9000"
    volumes:
      - minio_data_eleitoral:/data
    command: server /data
    deploy:
      replicas: 1

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8080:8080"
    command: ollama run llama3
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

volumes:
  postgres_data_eleitoral:
  minio_data_eleitoral: